### ISSUE TITLE
ready for production? 

### ISSUE THREAD

**Issue by siddo420** [localForage/localForage-memoryStorageDriver#3]
I wanted to use it as a fallback but wasn't sure about its stability.

why would anybody use it instead of https://github.com/localForage/localForage-sessionStorageWrapper? I haven't used it yet but wanted to know.

**Comment by thgreasi** [comment]
The original version of this driver was the dummyStorageDriver that is still used in the unit tests of the main localforage repo. Some users pointed that having the option to use such a volatile storage in their apps would be better than an "No driver supported" error. I've heard about people using it to achieve symmetric js code, for unit tests and also in order to support environments where even sessionStorage is not supported.
I haven't faced any issues while developing & using this, even with multiple instances.
Closing this for now, but still waiting for your feedback on this.

**Comment by siddo420** [comment]
Thanks.

I am thinking of trying sessionstorage before memorystorage ie. use memorystorage as last fallback

I assume it supports names and storeNames. See https://github.com/localForage/localForage/issues/484

**Comment by thgreasi** [comment]
Yes of course.
